name: "akso_project_cavan_keissa"

services:
  # Aplikasi wajib HTTP server
  nginx:
    image: nginx:latest
    container_name: nginx_server
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    configs:
      - source: nginx_config_main
        target: /etc/nginx/nginx.conf  
      - source: nginx_conf_d
        target: /etc/nginx/conf.d  
    networks:
      - app-network
    depends_on:
      - redis
      - mysql

  # Aplikasi wajib database server
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: redis_server
      MYSQL_USER: sada24
      MYSQL_PASSWORD: akso456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    configs:
      - source: mysql_config_main
        target: /etc/mysql/my.cnf  
    networks:
      - app-network

  # Aplikasi message queue
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    networks:
      - app-network
    command: ["redis-server", "--requirepass", "your_secure_password"]  
    restart: always  

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  mysql_data:

configs:
  nginx_config_main:
    file: ./nginx_config/nginx.conf  
  nginx_conf_d:
    file: ./nginx_config/conf.d  
  mysql_config_main:
    file: ./mysql_config/my.cnf  
